// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUvotxOoUL0Z81ZQSqqVnEpMpIZSEhPo',
    appId: '1:805337517924:web:f1d9cc21169d4ad9fef471',
    messagingSenderId: '805337517924',
    projectId: 'vibetag-27076',
    authDomain: 'vibetag-27076.firebaseapp.com',
    storageBucket: 'vibetag-27076.appspot.com',
    measurementId: 'G-3XMHHZXHLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQh8LqhvXIrAwk2Zc5jgsSLc-AL8kXCE',
    appId: '1:805337517924:android:ba54035442c6ec4ffef471',
    messagingSenderId: '805337517924',
    projectId: 'vibetag-27076',
    storageBucket: 'vibetag-27076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd8_Wo8bstHmK33I4JHyrPyxU4mL5HipI',
    appId: '1:805337517924:ios:ed7e639dfb1787b8fef471',
    messagingSenderId: '805337517924',
    projectId: 'vibetag-27076',
    storageBucket: 'vibetag-27076.appspot.com',
    iosClientId: '805337517924-o7auqt701b05a64303nmcs59bemuetpg.apps.googleusercontent.com',
    iosBundleId: 'com.vibetag.vibe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd8_Wo8bstHmK33I4JHyrPyxU4mL5HipI',
    appId: '1:805337517924:ios:ed7e639dfb1787b8fef471',
    messagingSenderId: '805337517924',
    projectId: 'vibetag-27076',
    storageBucket: 'vibetag-27076.appspot.com',
    iosClientId: '805337517924-o7auqt701b05a64303nmcs59bemuetpg.apps.googleusercontent.com',
    iosBundleId: 'com.vibetag.vibe.app',
  );
}
